FROM node:lts-buster

WORKDIR /workspaces

COPY ["./packages/server/package.json", "./packages/server/yarn.lock", "./"]

RUN yarn install

COPY ./packages/server/ .

ENV DATABASE_URL=postgresql://budgets:budgets@budgets-postgres:5432/budgets?schema=public

RUN echo "DATABASE_URL=$DATABASE_URL" > .env

EXPOSE 3333

CMD ["yarn" ,"run" , "dev"]